/**
 * MOCK AUTHENTICATION DATA — DEVELOPMENT ONLY
 *
 * ⚠️ These are fixtures, not credentials. Nothing here is a secret, nothing here
 * grants access to anything real, and none of it may survive into a production
 * build. `AppConfig.features.useMockServices` is the switch that retires it.
 *
 * Every mock account and the mock code live here rather than in a screen. A
 * screen containing `if (code === '123456')` would have to be edited when the
 * backend arrives, which is exactly the migration the service layer exists to
 * avoid.
 */

import { AppConfig } from '@/core/config/AppConfig';
import type { AuthUser } from '@/features/auth/types';
import { normalisePhone } from '@/shared/validation/phone';

/** The one-time code MockAuthService accepts, for customers and vendors alike. */
export const MOCK_OTP_CODE = '123456';

/** How long a mock one-time code stays valid. */
export const MOCK_OTP_TTL_SECONDS = 300;

/** Cooldown before the UI may offer "resend". */
export const MOCK_OTP_RESEND_AFTER_SECONDS = 30;


export interface MockAccount {
  /** Digits only. Compared after normalisation, so formatting does not matter. */
  phone: string;
  user: AuthUser;
  /**
   * Vendors only: the permanent auth code from a completed onboarding. Seeded so
   * the returning-vendor sign-in path is testable without registering first.
   */
  vendorAuthCode?: string;
}

/**
 * Accounts that already exist before any registration happens.
 *
 * Customer  9876543210                         → one-time code 123456
 * Vendor    9000000001 + FX-VENDOR-DEMO-CODE   → already onboarded, signs straight in
 *
 * Vendors created through the registration flow are held in memory by
 * MockAuthService for the life of the app process.
 */
export const MOCK_ACCOUNTS: readonly MockAccount[] = Object.freeze([
  {
    phone: '9876543210',
    user: {
      id: 'usr_customer_1',
      firstName: 'Asha',
      lastName: 'Patel',
      phone: '9876543210',
      role: 'customer',
    },
  },
  {
    phone: '9000000001',
    vendorAuthCode: 'FX-VENDOR-DEMO-CODE',
    user: {
      id: 'usr_vendor_1',
      firstName: 'Ravi',
      lastName: 'Kumar',
      phone: '9000000001',
      role: 'vendor',
    },
  },
]);

/**
 * Finds a seeded account by phone. Matches on trailing digits so a number
 * entered with a country code still resolves.
 */
export function findMockAccount(phone: string): MockAccount | undefined {
  const digits = normalisePhone(phone);
  if (digits.length < AppConfig.phone.minDigits) {
    return undefined;
  }
  return MOCK_ACCOUNTS.find(account => digits.endsWith(account.phone));
}

/**
 * Masks a number for display, mirroring what a real backend returns so the app
 * never has to mask anything itself.
 */
export function maskPhone(phone: string): string {
  const digits = normalisePhone(phone);
  if (digits.length <= 4) {
    return digits;
  }
  return `${'•'.repeat(digits.length - 4)}${digits.slice(-4)}`;
}

/** Ambiguous glyphs removed, so a code read off a screen transcribes cleanly. */
const CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

/**
 * Produces a development stand-in for the permanent vendor auth code.
 *
 * ⚠️ Simulation only. The production code is generated by the backend, which is
 * the only party that can do so securely. Nothing here is cryptographically
 * meaningful and it must never be relied upon as such.
 */
export function generateMockVendorAuthCode(): string {
  const block = (length: number): string =>
    Array.from({ length }, () =>
      CODE_ALPHABET.charAt(Math.floor(Math.random() * CODE_ALPHABET.length)),
    ).join('');

  return `FX-${block(4)}-${block(4)}`;
}
